# ---- Build stage ----
FROM debian:stable-slim AS build

RUN apt-get update && apt-get install -y --no-install-recommends \
    g++ cmake make pkg-config git \
    libasio-dev libssl-dev nlohmann-json3-dev librabbitmq-dev curl libboost-all-dev \
    libhiredis-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY . .

RUN rm -rf build && mkdir build && cd build && \
    cmake .. -DCMAKE_BUILD_TYPE=Release && \
    make -j$(nproc)

# ---- Runtime stage ----
FROM debian:stable-slim AS runtime

RUN apt-get update && apt-get install -y --no-install-recommends \
    libssl3 librabbitmq4 curl libhiredis-dev \
 && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY --from=build /app/build/server /usr/local/bin/server
COPY --from=build /app/build/processor /usr/local/bin/processor

EXPOSE 8081

# Default to server, processor can override in docker-compose.yml
CMD ["server"]
