services:
  rabbitmq:
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=myuser
      - RABBITMQ_DEFAULT_PASS=mypass
      - RABBITMQ_DEFAULT_VHOST=myvhost
    ports:
      - "5672:5672"
      - "15672:15672"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.server
    command: ["server"]
    depends_on:
      rabbitmq:
        condition: service_healthy
      postgres:
        condition: service_started
      redis:
        condition: service_started
    ports:
      - "8081:8081"
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=myuser
      - RABBITMQ_PASS=mypass
      - RABBITMQ_VHOST=myvhost
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=mydb
      - PGUSER=myuser
      - PGPASSWORD=mypass

  processor:
    build:
      context: .
      dockerfile: Dockerfile.processor
    command: ["processor"]
    depends_on:
      rabbitmq:
        condition: service_healthy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp:/tmp
    environment:
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_PORT=5672
      - RABBITMQ_USER=myuser
      - RABBITMQ_PASS=mypass
      - RABBITMQ_VHOST=myvhost
      - PGHOST=postgres
      - PGPORT=5432
      - PGDATABASE=mydb
      - PGUSER=myuser
      - PGPASSWORD=mypass

  runner:
    build: 
      context: ./runner
      dockerfile: Dockerfile.runner
    container_name: runner
    image: runner:latest

  redis:
    image: redis:7
    command: ["redis-server", "--appendonly", "yes"]
    ports:
      - "6379:6379"

  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=mydb
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypass
    ports:
      - "5432:5432"
    volumes:
      - ./db/migrations/001_init.sql:/docker-entrypoint-initdb.d/init.sql
