FROM debian:12-slim

RUN apt-get update && apt-get install -y \
    g++ \
    python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*

RUN useradd -ms /bin/bash runner
USER runner

WORKDIR /workspace
